mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from nlp.views import index

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('nlp/', include('nlp.urls')),
    path('', index, name='index'),
]

nlp/urls.py
from django.urls import path
from . import views

app_name = 'nlp'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('imagepoem/', views.image_poem, name='image_poem')
    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    # 定义了一个关系。这将告诉 Django，每个 Choice 对象都关联到一个 Question 对象
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.http import Http404
from django.views import generic
from django.utils import timezone
# 视图
'''
在 Django 中，网页和其他内容都是从视图派生而来。
每一个视图表现为一个 Python 函数（或者说方法，如果是在基于类的视图里的话）。
Django 将会根据用户请求的 URL 来选择使用哪个视图
（更准确的说，是根据 URL 中域名之后的部分）。
'''


def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_question_list': latest_question_list,
    # }
    # # output = ','.join([q.question_text for q in latest_question_list])
    # return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html')


def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{%  load static %}
<!DOCTYPE html>
<html>

<head>
    <title>为你写诗</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'nlp/main.css' %}">
    　　<meta name="viewport" content="width=device-width, initial-scale=1" />

    <style>
    *{
      box-sizing: border-box;
    }
    body {
      font-family: Arial;
      padding: 0px;
    }


    /* 创建三个不相等的列 */
    .column {
      float: left;
      padding: 10px;
    }
    /* 左右两侧宽度 */
    .column.side {
      width: 25%;
    }
    /* 中间区域宽度 */
    .column.middle {
      width: 50%;
    }
    .column.mean {
      width: 33%;
    }


    input[type=text]
    {
      {#position: relative;#}
      {#left: 40%;#}
        position: relative;
      width: 100%;
      padding: 12px 20px;
      {#margin: 8px 0;#}
      display: inline-block;
      border: 2px solid #ccc;
      border-radius: 4px;
    }
    input[type=text]:focus{
        background: #fdecfb;
    }

    .file
    {
        position: relative;
        width: 30%;
        padding: 10px 10px;
      {#margin: 8px 0;#}
      display: inline-block;
      border: 2px solid #ccc;
      border-radius: 4px;
        text-align: center;
    }
    .file input {
        position: absolute;
        font-size: 0.1px;
        right: 0;
        top: 0;
        opacity: 0;
    }
    .file label{
        text-align: center;
        font-size: 0.8em;
    }
    .file:hover {
        background: #fdecfb;
        border-color: #f320b7;
        color: #004974;
        text-decoration: none;
    }


    select
    {
        position: relative;
        {#left: 10%;#}
        width: 100%;
        padding: 10px 20px;
        {#margin: 8px 0;#}
        display: inline-block;
        border: 2px solid #ccc;
        border-radius: 4px;
        font-size: 0.6em;
        text-align: center;
    }
    .select_title{
        position: relative;
        {#left: 25%;#}
        width: 100%;
        padding: 2px 20px;
        {#margin: 8px 0;#}
        display: inline-block;
        {#border: 2px none #ccc;#}
        {#border-radius: 4px;#}
        font-size: 0.9em;
        letter-spacing: 3px;
        text-align: center;
        {#color: #ff00f1;#}
    }

/* 诗词显示框 */
.fakepoem {
    position: relative;
    left: 20%;
    width: 60%;
    height: 8em;
  {#padding: 20px;#}
    border-style: dashed;
    font-size: 2em;
    text-align: center;
}

/* 列后面清除浮动 */
    .row:after {
      content: "";
      display: table;
      clear: both;
        {#padding: 15px;#}
    }

    .main{
        width: 100%;
        height: 100%;
        position: absolute;
    }
    .quarter-div_header{
        width: 100%;
        height: 20%;
    }
    /* 头部标题 */
    .header {
        padding: 0.5em;
        text-align: center;
    }
    .header h1 {
        font-size: 2em;
        letter-spacing: 0.5em;
        color: #ff589a;
    }
    .header p {
        font-size: 0.7em;
        letter-spacing: 0.2em;
    }


    .quarter-div_input{
        width: 100%;
        height: 10%;
    }
    .quarter-div_button{
        width: 100%;
        height: 5%;
    }
    .quarter-div_select{
        width: 100%;
        height: 15%;
    }
    .quarter-div_output{
        width: 100%;
        height: 50%;
    }


    button {
        position: relative;
        left: 45%;
        width: 10%;
        background-color: #cddaff;
        color: white;
        padding: 14px 20px;
        /*margin: 8px 0;*/
        border: 2px solid #ccc;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #fdc7e7;
    }

    </style>

    <script type="text/javascript">
        function ProcessFile(e) {
            console.log('click file');
            let file = document.getElementById('image_input').files[0];
            if (file) {
                var reader = new FileReader();
                reader.onload = function (event) {
                    var txt = event.target.result;
                    var input_img = document.getElementById('output_image');
                    var text_input = document.getElementById('keyword_input');
                    text_input.value = "";
                    text_input.placeholder = "已选择一张图片";
                    input_img.src = txt; //将图片base64字符串赋值给img的src
                    {#input_img.height = 100;#}
                    {#input_img.width = 100;#}
                    {#document.getElementById("result").appendChild(img);#}
                };
            }
            reader.readAsDataURL(file);
        }

        function Processtext(e) {
            console.log('click text');
                    let input_img = document.getElementById('output_image');
                    let text_input = document.getElementById('keyword_input');
                    text_input.placeholder = "请输入一个关键词|或右侧选择一张图片";
                    text_input.value = this.value;
                    input_img.src = ""; //将图片base64字符串赋值给img的src
                    let file = document.getElementById('image_input');
                    file.value='';
            }
        function contentLoaded() {
            document.getElementById('image_input').addEventListener('change', ProcessFile, false);
        }

        function textLoaded() {
            document.getElementById('keyword_input').addEventListener('click', Processtext, false);
            {#document.getElementById('keyword_input').addEventListener(type=)#}
        }

        window.addEventListener("DOMContentLoaded", contentLoaded, false);
        window.addEventListener("DOMContentLoaded", textLoaded, false);
    </script>
</head>


<body>
<div class="main">
    <div class="quarter-div_header">
        <div class="header">
            <h1>为你写诗</h1>
            <p>天青色等烟雨 而我在等你</p>
        </div>
    </div>

{#输入框#}
    <div class="quarter-div_input">
        <div class="row">
            <div class="column side">
                <b></b>
            </div>
            <div class="column middle">
                <input type="text" id="keyword_input" name="keyword_input" placeholder="请输入一个关键词|或右侧选择一张图片">
            </div>
            <div class="column side">
                <div class="file">
                    <label for="image_input">选择图片</label>
                    <input type="file" id="image_input" name="image_input" accept="image/jpg, image/jpeg, image/png">
                </div>
            </div>
        </div>
    </div>

{#选择框#}
    <div class="quarter-div_select">
        <div class="row">
          <div class="column side">
            <p></p>
          </div>

          <div class="column middle">
                <div class="column mean">
                    <b class="select_title">选择生活经历</b><br>
                    <select name="living_experience" id="living_experience">
                        <option value="0" selected>军旅生涯</option>
                        <option value="1">田园生活</option>
                        <option value="2">其他</option>
                        <option value="-1">不指定</option>
                    </select>
                </div>

                <div class="column mean">
                    <b class="select_title">选择诗体裁</b><br>
                    <select name="poem_length" id="poem_length">
                        <option value="5" selected>5言</option>
                        <option value="7">7言</option>
                    </select>
                </div>

                <div class="column mean">
                    <b class="select_title">选择历史背景</b><br>
                    <select name="historical_background" id="historical_background">
                        <option value="0" selected>盛世</option>
                        <option value="1">乱世</option>
                        <option value="1">不指定</option>
                    </select>
                </div>

          </div>

          <div class="column side">
        {#      <img id="output_image" src="" alt="" height="250px" width="250px"/>#}
          </div>
        </div>
    </div>

    <div class="quarter-div_button">
        {#提交按钮#}
        <div>
            <button id="lgbut_compute">作诗</button>
        </div>
</div>


{#诗显示#}
    <div class="quarter-div_output">
         <div class="row">
              <div class="column side">
                <p></p>
              </div>
             <div class="column middle">
                 <p id="poem_produce" class="fakepoem">
             </div>

             <div class="column side">
                 <img id="output_image" src="" alt="" style=" position: relative;left:20%;
                 padding:2em 0em;width: 60%;height: auto"/>
             </div>

         </div>
    </div>

</div>




    <script>
        function ShowResult(data) {
            let v = data['img64'];
            {#var img = document.createElement("img_new");#}
            {#let out_img = document.getElementById('output_image');#}
            {#out_img.src = "data:image/jpeg;base64, " + v;#}
            {#out_img.height = 250;#}
            {#out_img.width = 250;#}
            {#document.getElementById("result_new").appendChild(img);#}
            {#ewmtp.src = "data:image/jpeg;base64, " + v;#}

            let poem_produce = document.getElementById('poem_produce');
            console.log(poem_produce.innerText);
            poem_produce.innerText = data['poem'];

        }
    </script>
    <script>
        $('#lgbut_compute').click(function () {
            formdata = new FormData();
            console.log($("#keyword_input").val());
            var file = $("#image_input")[0].files[0];
            console.log(file);
            formdata.append("image", file);
            formdata.append("poem_length", $("#poem_length").val());
            formdata.append("key_word", $("#keyword_input").val());
            formdata.append("living_experience", $("#living_experience").val());
            formdata.append("historical_background", $("#historical_background").val());
            $.ajax({
                url: "{% url 'nlp:image_poem' %}", //调用django服务器计算函数
                type: 'POST', //请求类型
                data: formdata,
                dataType: 'json', //期望获得的响应类型为json
                processData: false,
                contentType: false,
                success: ShowResult //在请求成功之后调用该回调函数输出结果
            })
        })
    </script>
</body>


</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>